# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8306172ea0ba709647c3b406d45e00a71653a0b7a04a30d55b22a4a6e5e0aaa6b31a0f163fc0b8e0219e4b5ffdf8072eba283c8e91594cc0c5d2267ca85a72f

test:
  secret_key_base: 866688adca81f93e473ee8f4bdc128dfd80fecc1e07f7a8444d3e6a50101819ee308a4a36a5d553fda5ae91ff791f41e8012279f6cc7e6d70b3ddcee89cae665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
